# Generated by Django 4.2.5 on 2023-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('один раз', 'one_time'), ('ежедневно', 'daily'), ('еженедельно', 'weekly'), ('ежемесячно', 'monthly')], default='one', max_length=15, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('создана', 'created'), ('запущена', 'active'), ('завершена', 'completed')], default='new', max_length=15, verbose_name='состояние'),
        ),
    ]
