# Generated by Django 4.2.5 on 2023-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_period_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('one_time', 'one_time'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='one_time', max_length=15, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('active', 'active'), ('completed', 'completed')], default='created', max_length=15, verbose_name='состояние'),
        ),
    ]
