# Generated by Django 4.2.6 on 2023-10-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_period_alter_mailing_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='MailingLog',
        ),
    ]
